name: pygeoglows
channels:
  - conda-forge
dependencies:
  - python>=3
  - cftime
  - dask >=2024
  - fastparquet
  - HydroErr
  - hydrostats
  - numpy >=1
  - pandas >=1
  - plotly >=5
  - requests
  - s3fs >=2024
  - scipy >=1
  - shapely >=2
  - xarray >=2024
  - zarr >=2,<3